About/urls.py
from django.urls import path
from . import views

app_name = 'About'
urlpatterns = [
    path('', views.index, name="About"),
]

Contact/urls.py
from django.urls import path
from . import views

app_name = 'Contact'
urlpatterns = [
    path('', views.index, name="Contact"),
]

Education/urls.py
from django.urls import path
from . import views

app_name = 'Education'
urlpatterns = [
    path('', views.index, name="Education"),
]

Experience/urls.py
from django.urls import path
from . import views

app_name = 'Experience'
urlpatterns = [
    path('', views.index, name="Experience"),
]

HerokuStory4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Homepage.urls')),
    path('Contact/',include('Contact.urls')),
    path('About/',include('About.urls')),
    path('Experience/',include('Experience.urls')),
    path('Education/',include('Education.urls')),
    path('Skills/',include('Skills.urls'))
]

Homepage/urls.py
from django.urls import path
from . import views

app_name = 'Homepage'
urlpatterns = [
    path('', views.index, name="Homepage"),
]

Skills/urls.py
from django.urls import path
from . import views

app_name = 'Skills'
urlpatterns = [
    path('', views.index, name="Skills"),
]

About/models.py
from django.db import models

# Create your models here.

Contact/models.py
from django.db import models

class create_comment(models.Model):
    commentfield = models.CharField(max_length=300)
    time = models.DateTimeField()

    def __str__(self):
        return self.commentfield

Education/models.py
from django.db import models

# Create your models here.

Experience/models.py
from django.db import models

# Create your models here.

Homepage/models.py
from django.db import models

# Create your models here.

Skills/models.py
from django.db import models

# Create your models here.

About/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'About.html')

Contact/views.py
from django.shortcuts import render
from .models import create_comment
import datetime

def index(request):
    all_comment=create_comment.objects.all().order_by('time')
    context= {'all_comment': all_comment}
    if request.method == 'POST':
        comment=create_comment()
        comment.commentfield=request.POST.get('commentfield')
        comment.time=datetime.datetime.now()
        comment.save()
        return render(request, 'contact.html',context)
    else:
        return render(request, 'contact.html',context)

Education/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'Education.html')

Experience/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'Experience.html')

Homepage/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'Homepage.html')

Skills/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'Skills.html')

About/templates/About.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}

<!-- bagian about     -->
<div class="container-fluid" id="About">
    <div class="row">
        <div class="col-lg-4">
            <h1>ABOUT</h1>
            <img src="{% static 'assets/myphoto1.jpg' %}"  class="rounded-lg float-left">
        </div>
        <div class="col-lg-6">
            <p>My name is Audrey Annisa Datau and you can call me 
                    Audrey. I was born and grew up in Jakarta, Indonesia.<br>
                    <br> I am a hardworking and punctual individual with passion
                    for technology. I work well in team and also on my own. 
                    I am well organized and love to make plans about things 
                    that i will do.

            </p> 
        </div>
    </div>
</div>

{% endblock content %}

Contact/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact{% endblock title %}

{% block content %}
<!-- bagian contact/get in touch -->
<section id="contact">
    <br>
    <br>
    <h2>Get in Touch</h2>
    <h3> You can reach me through:</h3>
    <div class="button_cont" align="center">
        <a class="Email" href="mailto:audreydatau@gmail.com" target="_blank" rel="nofollow noopener">email</a>
        <a class="LinkedIn" href="https://www.linkedin.com/in/audrey-datau/" target="_blank" rel="nofollow noopener">LinkedIn</a>
        <a class="Instagram" href="https://www.instagram.com/audreydatau/" target="_blank" rel="nofollow noopener">Instagram</a>
    </div>
</section>

<section id="comment">
<div class="allcontent">
    <form method="POST" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="comment" class="labelcomment">Leave your comment down below!</label>
            <input type="text" class="form-control"  id="commentfield" placeholder="fill with your comment" name="commentfield">
        </div>
        <button type="submit" class="submit" id='submit'>Submit</button>
    </form>
</div>


<div class="table_data" id="table_data">
        <table class="table table-hover" id="table">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Comment</th>
            <th scope="col">Date/time</th>
        </tr>
        </thead>
            <div class="contentcomment">
                <tbody>
                {% for s in all_comment %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ s.commentfield }}</td>
                        <td>{{ s.time }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </div>
        </table>
</div>         
{% endblock content %}

Education/templates/Education.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Education{% endblock title %}

{% block content %}

<!-- bagian Education -->
<div class="AllEducation"  id="Education">
    <h1>EDUCATION</h1>
    <div class="contenteducation">

        <div class="Education1">
            <p class="label success new-label">
                <h3 class="align">Bachelor of Information Systems, Universitas Indonesia <h4><i>2018 - present</i> </h4>  </h3> 
                <h3 class="add-label"><Strong>Bachelor of Information Systems, Universitas Indonesia</Strong>
                    <br>Learning to combine computer concepts with business and management. 
                    <br>The goal is to 'bridge' between business needs and applications in the IT field.
                </h3>
            </p>
        </div>
    
        <div class="Education2">
                <p class="label success new-label">
                <h3 class="align">61 Senior High School <h4><i>2015 - 2018</i> </h4> </h3> 
                </p>
        </div>
    </div>
</div>

{% endblock content %}

Experience/templates/Experience.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Experience{% endblock title %}

{% block content %}

<!-- bagian Experience -->
<div class="AllExperience"  id="Experience">
    <h1>EXPERIENCE</h1>
    <div class="contentexperience">

        <div class="Experience1">
                <p class="label success new-label">
                <h3 class="align">Universitas Indonesia <h4><i>September 2019 - present</i> </h4>  </h3> 
                <h3 class="add-label"><strong>Universitas Indonesia 
                <br> Teaching Assistant for Programming Foundation 1 & 2 </strong>
                <br> Help and make students comfortable with programming, arranging tutorial problems, scoring students tutorial and assignments.
                </h3></p>
        </div>
        
        <div class="Experience2">
                <p class="label success new-label">
                <h3 class="align">BEM FASILKOM UI <h4><i>February 2019 - December 2019 </i> </h4>  </h3> 
                <h3 class="add-label"><strong>BEM FASILKOM UI 
                <br> Public Relations Staff </strong>
                <br> Maintain the publication of BEM Fasilkom UI in social media  and be a liason between
                <br> BEM & external parties both inside and outside faculty.
                </h3></p>
        </div>

        <div class="Experience3">
                <p class="label success new-label">
                <h3 class="align">COMPFEST <h4><i> March 2019 - September 2019 </i> </h4>   </h3>
                <h3 class="add-label"> <strong>COMPFEST
                <br> Marketing Staff</strong>
                <br> Maintain all social media of COMPFEST.
                </h3></p>
        </div>

        <div class="Experience4">
                <p class="label success new-label">
                <h3 class="align">CROPS PATRIOTS <h4><i> April 2017 </i> </h4>   </h3>
                <h3 class="add-label"><strong>CROPS PATRIOTS
                <br> Vice Project Officer</strong>
                <br> Be the right handman for the project officer.
                </h3></p>
        </div>
        
    </div>
</div>

{% endblock content %}

Homepage/templates/Homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

<!-- bagian landing page awal -->
<section id="Home">
    <br>
    <h1>HELLO, I'M <br>
    AUDREY ANNISA DATAU!</h1>
    <h3>2nd year information system student</h3>
    <a class="btn btn-outline-dark btn-lg" href="{% url 'About:About' %}">More</a>
</section>

{% endblock content %}
        

Skills/templates/Skills.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Skills{% endblock title %}

{% block content %}

<!-- bagian Skills -->
<div class="Skills"  id="Skills">
    <h1>Skills</h1>
    <div class="contentskills">
        <div class="SkillsLanguages">
                <h3>Languages</h3>
                <h5>Python &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp;  CSS</h5>
                <h5>Java &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Java Script</h5>
                <h5>HTML</h5>
        </div>
    
        <div class="SkillsOthers">
                <br>
                <h3>Others</h3>
                <h5>Adobe Illustrator</h5>
                <h5>Adobe Photoshop</h5>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<html>
    <head>
        <title>Audrey Datau | {% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

         <!-- menghubungkan dengan css dan bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="Stylesheet" href="{% static 'css/Story4.css' %}">

        <!-- membuat icon judul website-->
        <link rel="icon" href="{% static 'assets/logo.png' %}" type="image/icon">

        <!-- menggunakan jenis font yang sesuai -->
        <link href="https://fonts.googleapis.com/css?family=Mukta+Vaani&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- bagian navigasi yang paling atas dan terdapat logo paling kiri -->
        <div class="header">
            <nav class="navbar fixed-top navbar-light">
            <a class="navbar-brand" href="{% url 'Homepage:Homepage' %}">
            <img src="{% static 'assets/logo.png' %}" width="50" height="30" alt="">
            </a>
            <a href="#" class="openButton" onclick="openNav()"><img src="{% static 'assets/nav.png' %}" width="50" height="50"></a>
            </nav>        
        </div>

        <!-- mengatur hamburger navbar yang paling kanan -->
        <div id="nav" class="overlay">
            <a href="#" class="closeButton" onclick="closeNav()">X</a>
                <div class="overlay__content">
                    <a href="{% url 'Homepage:Homepage' %}" onclick="closeNav()">Home</a>
                    <a href="{% url 'About:About' %}" onclick="closeNav()">About</a>
                    <a href="{% url 'Experience:Experience' %}" onclick="closeNav()">Experience</a>
                    <a href="{% url 'Education:Education' %}" onclick="closeNav()">Education</a>
                    <a href="{% url 'Skills:Skills' %}" onclick="closeNav()">Skills</a>
                    <a href="{% url 'Contact:Contact' %}" onclick="closeNav()">Contact</a>
                </div>
        </div>

        
        {% block content %}
        {% endblock %}

        <!-- menghubungkan dengan file javascript -->
        <script src="{% static 'js/Story4.js' %}"> </script>
    </body>
</html>
    